language: node_js
node_js:
  - "node"
cache: npm
script: npm run build
branches:
  only:
    - gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "0d1df233ae5342dd4dfee183af04503b66a7cd7a"
  local_dir: dist
  on:
    branch: gh-pages